project:
  type: website
  output-dir: docs

website:
  title: "SolplotsBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Max-Fortune
      - icon: twitter
        href: https://www.instagram.com/solplots/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

